name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install # replace with your package manager command

      - name: Build site
        run: yarn build # replace with your build command

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # replace with your GitHub Pages branch name
          folder: pearl-portal/build # replace with your build directory
          token: ${{ secrets.ACCESS_TOKEN }} # replace with your access token name